title: My First GitHub Page!
author: Christophe L.
email: somefakeaddress@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  just some placeholder

# social links
twitter_username: @somefaketwitter
github_username:  christopheliu

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
